GetStream/stream-chat-go

- channel.go
- channel_member.go
- channel_type.go
- client.go
- device.go
- event.go
- go.mod
- go.sum
- message.go
- message_type.go
- mute.go
- options.go
- reaction.go
- stream_chat.go
- user.go
> Core implementation

- client.go
- client_test.go
> temporary fix for jwt with rounding

- channel.go
- channel_test.go
> CreateChannel: channel id is optional when members are present

- channel.go
Simplify member check condition in channel create.
> channel: simplify member check for create

- README.md
Run gofmt on readme example and also trim extra whitespace.
> readme: gofmt readme

- README.md
- app.go
- app_test.go
- channel.go
- channel_test.go
- channel_type.go
- client.go
- client_test.go
- message.go
- query.go
- query_test.go
- stream_chat.go
- stream_chat_easyjson.go
- user.go
- utils_test.go
Implementation of missing methods:
1. GetApp, UpdateAppSettings
2. UpdateUser
3. ReactivateUser
4. GetMessage
5. Flag\Unflag message
6. UpdateChannelType
7. VerifyWebhook
8. channel.Query
9. Search
> Missing api calls

- go.mod
- go.sum
- stream_chat_easyjson.go
- user.go
> Fix issue with ExtraData fields missing

- go.sum
- stream_chat_easyjson.go
- user.go
- user_test.go
Example
```go
// add a new field
update := PartialUserUpdate{
ID: user.ID,
Set: map[string]interface{}{
"field": true,
},
}
user, err := c.PartialUpdateUser(update)
// remove a new field
update := PartialUserUpdate{
ID: user.ID,
Unset: []string{"field"},
}
user, err := c.PartialUpdateUser(update)
// change nested field
update := PartialUserUpdate{
ID: user.ID,
Set: map[string]interface{}{
"field.nested": "data",
},
}
user, err := c.PartialUpdateUser(update)
// replace object field
update := PartialUserUpdate{
ID: user.ID,
Set: map[string]interface{}{
"field": map[string]interface{}{
"subfield": "data"
},
},
}
user, err := c.PartialUpdateUser(update)
...
```
> UpdateUsers: allow partial update

- user.go
- user_test.go
> fix UnmuteUsers, add test

- channel.go
- channel_test.go
- message.go
- stream_chat.go
- stream_chat_easyjson.go
- user.go
…tags
- [*] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required).
- [*] The code changes follow best practices
- [*] Code changes are tested (add some information if not applicable)
> system message on channel operations

- README.md
- go.mod
> Add version suffix to module

- .golangci.yml
- channel.go
- message.go
- query.go
- query_test.go
- reaction.go
- reaction_test.go
- run-lint.sh
- user.go
Disabled some of new linters that has overlap functionality and are against our style of writing.
> Bump golangci-lint

- channel.go
- channel_test.go
- stream_chat.go
Allow passing a message when:
promoting  / demoting moderators
ban / unban a user (API call only, not for /ban /unban commands)
invite user
accept invite
reject invite
> options for several methods

- channel.go
- client.go
- device.go
- reaction.go
- user.go
- utils_test.go
> Combine same type params

- .github/workerflows/go.yml
> Integrate github actions

- README.md
> Add actions badge to readme

- .travis.yml
drop travis config since github actions are in-place
> Drop travis

- .github/workflows/go.yml
* also, use checkout v2
* add coverage
> Add matrix build for go1.12

- CHANGELOG.md
> Release v2.0.2

- channel.go
- stream_chat.go
> Implement clear history on channel hide

- .github/workflows/go.yml
- README.md
> Name badge to build

- README.md
Fixes #53
Correct install command
> Update readme for install command

- client.go
- version.go
> Add version client header

- CHANGELOG.md
- version.go
Update changelog and bump version
> Update changelog for v2.2.0

- client_test.go
- run-lint.sh
Bump lint and use bytes equal instead of reflect.
> Bump lint and use bytes instead of reflect

- CHANGELOG.md
- version.go
> Update changelog for v2.2.1

- README.md
- channel.go
- channel_test.go
- client.go
- query.go
- stream_chat_easyjson.go
- user.go
This is a fork of #60 as @thesyncim had already started down this path. I just took it a step further and did some additional cleanup of query options.
This should also fix #74
> Channel Mutes & Cleanup Query Options

- client.go
> Fix verify webhook

- app_test.go
- channel_test.go
- channel_type_test.go
- client_test.go
- device_test.go
- query_test.go
- reaction_test.go
- user_test.go
- utils_test.go
> Drop test wrappers

- channel.go
- stream_chat_easyjson.go
> Add extra data support for channel

- .golangci.yml
- app.go
- channel.go
- channel_config.go
- channel_type.go
- client.go
- device.go
- event.go
- message.go
- query.go
- reaction.go
- run-lint.sh
- stream_chat.go
- user.go
- version.go
* explicit checks
* better adaptation of golint rules
* improve config and bump version
> Improve lint and comments

- query.go
- stream_chat.go
- stream_chat_easyjson.go
- user.go
- user_test.go
Added options to `MuteUser` and `MuteUsers` to support the recently added `timeout` option for Mute expiration
> User mute expiration

- CHANGELOG.md
- version.go
@ferhatelmas I've also tagged it but I'm not sure about the process to release it, how would I do that?
> Updated version and changelog for 2.4.0

- channel.go
> Request state in channel query

- .golangci.yml
- channel.go
- channel_test.go
- channel_type.go
- client_test.go
- event.go
- query.go
- query_test.go
- run-lint.sh
- user_test.go
> Bump lint, drop impi

- channel.go
- channel_test.go
> Add query members support

- channel.go
- channel_test.go
- message.go
- stream_chat.go
> [CHAT-1159] import channel messages

- client.go
- client_test.go
> Use string for token

- .github/workflows/go.yml
- go.mod
> Drop <go1.14

- channel.go
- channel_test.go
> Correct CreateChannel and QueryMembers test

- query.go
- query_test.go
> Add message/member limits to query channels

- channel.go
> Ensure un/mute works without querying

- client_test.go
- event.go
This PR adds
- the `SendUserCustomEvent` method for sending custom event to a user
- a new `UserCustomEvent` type
⚠️ This shouldn't be merge until the API integration
> Add SendUserCustomEvent method

- client.go
> Use proxy dns

- channel_type.go
- client_test.go
- utils_test.go
* upsert user for test so that precondition works
* clear old channel types automatically from previous failing tests
> Make CI green

- channel.go
This PR adds the `Disabled` field to the `Channel` type.
> [CHAT-1652] Add disabled field

- client.go
- client_test.go
> Make issuedAt backward compatible

- event.go
> Add missing channel.created event

- query.go
- query_test.go
> Feature: Search endpoint improvements

- message.go
> Add support for hard deleting messages

- channel.go
- channel_test.go
- message.go
- message_test.go
- user.go
- user_test.go
Add ShadowBan, RemoveShadowBan, PinMessage & UnPinMessage methods.
> [CHAT-2592] ShadowBan & Pin methods

- async_tasks.go
transfer channel ownership while hard-deleting users through new_channel_owner_id option
> [CHAT-2437] Transfer channel ownership

- .gitignore
- CONTRIBUTING.md
- README.md
- channel.go
- channel_test.go
Add truncate options. Using the splat operator to keep backward compatibility.
> feat: add truncate options

- .github/workflows/go.yml
- .github/workflows/lint.yml
- channel.go
- channel_test.go
- channel_type.go
- channel_type_test.go
- client.go
- permission_client.go
- permission_client_test.go
> feat: add permissions v2

- .github/CODEOWNERS
- .github/workflows/go.yml
- .github/workflows/initiate_release.yml
- .github/workflows/lint.yml
- .github/workflows/release.yml
- .versionrc.js
- CONTRIBUTING.md
- scripts/get_changelog_diff.js
Here's how an example looks like: https://github.com/GetStream/stream-chat-net/pull/89
> ci: add release flow

- async_tasks_test.go
- ban.go
- ban_test.go
- channel.go
- channel_test.go
- command.go
- command_test.go
- message.go
- query_test.go
- user.go
- user_test.go
#160 was reverted, this PR adds changes back.
> Improve API

- README.md
- app.go
- app_test.go
- async_tasks.go
- async_tasks_test.go
- blocklist.go
- blocklist_test.go
- channel.go
- channel_test.go
- client.go
- user.go
- user_test.go
> feat: full feature parity

- app.go
> feat: extend app config

- client.go
> feat: enhance connection pooling

- .github/workflows/ci.yml
- ban.go
- import.go
- import_test.go
- query.go
- Add Offset and Limit to import endpoints
> feat: add offset and limit to listimports

- .versionrc.js
Bump go.mod file with major version
> ci: bump go.mod file

- app.go
- message.go
- message_test.go
- user.go
add translate message endpoint
> feat: add translate message endpoint

- client.go
- utils_test.go
Good to use in CLI to reduce maintenance costs.
> chore: export base url

- message.go
Fixes https://github.com/GetStream/chat/issues/3392
> Add missing fields to Message type

- import.go
- import_test.go
added new private method CreateImportURL for internal use only
> feat: add CreateImportURL method

- client.go
- client_test.go
> fix: check if iat is zero

- import.go
- import_test.go
fixes https://github.com/GetStream/chat/issues/3501
> feat: added mode to createImport

- import.go
> fix: added missing field to ImportTask response

- import.go
> feat: added ImportMode type

- query.go
- query_test.go
- user.go
> feat: add new moderation apis

- app.go
- device.go
> feat: add push providers

- app.go
- device.go
> feat: add push provider fields

- app.go
- channel_config.go
> feat: add reminder fields

- README.md
- client.go
> feat: add timeout constructor

- .github/workflows/ci.yml
- .github/workflows/lint.yml
- .github/workflows/reviewdog.yml
> ci: set to gosetup v3

- reaction.go
- reaction_test.go
> refactor(reactions): reactions part of client instead of channel

- .github/workflows/ci.yml
- .gitignore
> ci: print code coverge

- app.go
> feat: add new props to pushprovider

- README.md
https://github.com/GetStream/stream-chat-go/issues/194
> docs(readme): fix code snippet

- app.go
- app_test.go
> Handle clearing in settings

- message.go
- message_test.go
> feat: pending messages

- event.go
> feat: event user unread message reminder

- user.go
> feat: add ability to delete/restore channels when deactivate/reactivate users

- channel_test.go
- message.go
> feat: sending system messages

- app.go
- app_test.go
- channel.go
- channel_config.go
- channel_test.go
- channel_type_test.go
- message.go
- message_test.go
> feat: adding pending property to message

- message.go
- message_test.go
> feat: keep channel hidden

- .github/workflows/ci.yml
- unread_counts.go
- unread_counts_test.go
Add support for unread count endpoints (batch endpoint is still unmerged)
> feat: add support for unread counts endpoints

- .github/CODEOWNERS
- channel.go
- channel_test.go
> Unread message count

- channel.go
- draft_test.go
- message.go
- message_history.go
- utils_test.go
> [CHA-606] add draft endpoints

- message.go
- message_test.go
We had missing properties when creating a `messageRequestMessage` from a `Message`.
> [CHA-0] add missing properties to message request

- .github/CODEOWNERS
Added 
- nijeesh
- slava
- faiz as code owners to the GO SDK
> [CHA-0] Update CODEOWNERS

- ban_test.go
- channel.go
- channel_test.go
- client_test.go
- draft_test.go
- message_history_test.go
- message_test.go
- query_test.go
- thread_test.go
- unread_counts_test.go
- utils_test.go
Reverts GetStream/stream-chat-go#334
> Revert "[CHA-941]: supporting passing member"

- channel.go
- channel_test.go
> [CHA-941]: update channel to accept ChannelMembers too

- thread_test.go
- user.go
- Update the return of DeactivateUsers and ReactivateUsers
> feat: Return AsyncTaskResponse for DeactivateUsers and ReactivateUsers

- event.go
- message.go
> [CHA-1113] Update response fields for delete for me feature

- app_test.go
- channel_test.go
- message_test.go
Fix failing webhook and restricted visibility tests
> Fix failing webhook and restricted visibility tests
