.golangci.yml, run-lint.sh
There is a new linter: gomnd
It's a magic number detector but it's
disabled due to its less benefits and multiple
false positives for hardcoded numbers in tests.
=> Bump golangci-lint to v1.22.2

client.go
currently requests with nil body always set the body to 'null'
example generated body for a get request
```
GET /channels?api_key=892s22ypvt6m&payload=%7B%22watch%22%3Afalse%2C%22state%22%3Atrue%2C%22presence%22%3Afalse%2C%22filter_conditions%22%3A%7B%22limit%22%3A1%2C%22id%22%3A%22222656533%22%7D%7D HTTP/1.1
Host: localhost:9000
User-Agent: Go-http-client/1.1
Transfer-Encoding: chunked
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzZXJ2ZXIiOnRydWV9.i0aGGmGBBVOA17ZDoEUPyuugjUKgm18wleyB8411-SU
Content-Type: application/json
Stream-Auth-Type: jwt
X-Stream-Client: stream-go-client
Accept-Encoding: gzip
1
n
3
ull
```
=> do not send "null" as body in request without body

README.md
According to the [docs](https://getstream.io/chat/docs/initialize_channel/?language=js), it looks like `members` should be used instead of `users` for the channel data
=> changing `users` to `members`

app_test.go, channel_test.go, channel_type_test.go, client.go, device_test.go, reaction_test.go, user_test.go
These are mostly examples I wrote for the website proper, but I decided they would fit well in here.
There are a few small changes that fall out side of that.
1. I added a small delay in one of the tests before test cleanup. This was due to it intermittently failing causing the tests to fail.
2. I added a `(*Client).Channel` function which makes it easier to get a channel with known values. It doesn't make an API call in and of itself, just gives you an object that can be used for API calls.
=> Add examples for documentation

reaction.go
The example provided in the documentation for GetReactions is incorrect. I've updated the docs.
Specifically the Options type is of `map[string][]string` which means the parameters have to be strings.
=> Fix quotation in documentation for GetReactions

.github/workflows/go.yml
Instead of running push and PR, just run PR.
Add go 1.14 and 1.15.
=> Improve action running and new go versions

channel.go
Members aren't always needed. Additionally, reserved fields can't be submitted.
=> Send members conditionally for query members

query.go, query_test.go
So we don't automatically omit 0, but also don't automatically set the limits to 0 if they're not specified
=> MessageLimit and MemberLimit should be pointers

rate_limits.go, rate_limits_test.go
This PR introduces support for the `GetRateLimits` endpoint, which returns the current rate limits quotas and usage.
The params are thought so that if they are empty/zero they won't be included in the call and the whole list of limits will be returned.
=> add GetRateLimits endpoint support

app.go, client.go, client_test.go, user.go
Adds token revocation helpers methods
- `RevokeTokens()`
- `RevokeUserToken()`
- `RevokeUsersTokens()`
also adds a `iat` param in `CreateToken()` to be set while token generation.
=> [CHAT-1650] Add revoke token methods and iat claim in createtoken

.golangci.yml, channel_config.go
This PR adds missing channel type options to `ChannelConfig`.
Also increased threshold for `hugeParam` linter:
```
channel.go:59:7: hugeParam: ch is heavy (376 bytes); consider passing it by pointer (gocritic)
func (ch Channel) cid() string {
^
channel.go:90:7: hugeParam: ch is heavy (376 bytes); consider passing it by pointer (gocritic)
func (ch Channel) MarshalJSON() ([]byte, error) {
```
=> Add missing options for channel config

channel_type.go
Currently commands that set to the `ChannelType` are not proxied to the `channelTypeRequest` when creating a channel type. This PR fixes this
=> Proxy command list to createTypeRequest when creating channel type

event.go
We already have the information in the route, we can remove it from the payload.
=> Remove target user id from payload on SendUserCustomEvent

async_tasks.go, async_tasks_test.go
This PR adds two new methods:
- `client.DeleteChannels` which allows to delete N channels asynchronously 
- `client.GetTask` which allows to get the status of a task which has been ran asynchronously
=> [CHAT-1823] Add DeleteChannels method

message.go, query_test.go, user.go, user_test.go
This is deprecated and does nothing from now. Since we do major, good to drop for SDK
=> Drop unflag message/user

app.go, app_test.go, async_tasks.go, async_tasks_test.go, channel.go, channel_test.go, channel_type.go, channel_type_test.go, client.go, client_test.go, command.go, command_test.go, device.go, device_test.go, event.go, event_test.go, http.go, http_test.go, message.go, message_test.go, permission_client.go, permission_client_test.go, query.go, query_test.go, rate_limits.go, reaction.go, reaction_test.go, user.go, user_test.go, utils_test.go
This PR adds a base response type `Response` which holds rate limit information computed from response headers.
Breaking changes:
- All methods return now two parameter: a `*Response` and an error
- Except the ones that return specific types, those types have now a `Response` embedded
- Some types have been now exposed eg. `sendFileResponse` is now `SendFileResponse` and contain the `Response`
=> Add base response with rate limit info

http.go
conn won't be used if there is an issue otherwise.
=> Close body in correct place

.github/workflows/go.yml, app.go, channel_type.go, channel_type_test.go
In order to fill up the code snippet examples in the [Permission V2 docs page](https://getstream.io/chat/docs/java/user_permissions/?preview=1&language=go), we need to be able to update grants on channel type level.
So basically this is support for ChannelType grants.
=> feat: add grants to channeltype

app_test.go, async_tasks_test.go, ban_test.go, channel_test.go, channel_type_test.go, client_test.go, command_test.go, device_test.go, event_test.go, http_test.go, message_test.go, query_test.go, rate_limits_test.go, reaction_test.go, user_test.go, utils_test.go
- Declare context once
- Introduce `t.Cleanup()` everywhere
=> test: refactor tests for cleanup

app.go
The response includes `providers` which was not included in the struct.
=> fix: include push providers in push notification fields

.github/workflows/ci.yml, message.go
=> fix: payload for sendmessage to prevent upsert user

message_history.go, message_history_test.go
Add ability to query message history.
=> feat: add message history

query.go, query_test.go, user_test.go
This adds support for querying deactivated users.
Note: This is a breaking change since the signature of the `QueryUsers` methods had to change to accept a new type. The updated tests show how the signature must be updated
=> feat: add support for querying deactivated users

.github/workflows/ci.yml, channel.go, channel_test.go
https://linear.app/stream/issue/CHA-14/members-custom-data-go-sdk
=> [CHA-14] Added support for pinning, archiving channels and partial member update

.github/CODEOWNERS, .github/workflows/ci.yml, .github/workflows/lint.yml, .github/workflows/reviewdog.yml, .github/workflows/scheduled_test.yml, async_tasks.go, async_tasks_test.go, go.mod, go.sum
Adds support for the async export users endpoint in the Chat API.
=> add support for async export users endpoint

channel.go, query.go
From Js SDK
```typescript
export type ChannelAPIResponse<StreamChatGenerics extends ExtendableGenerics = DefaultGenerics> = {
channel: ChannelResponse<StreamChatGenerics>;
members: ChannelMemberResponse<StreamChatGenerics>[];
messages: MessageResponse<StreamChatGenerics>[];
pinned_messages: MessageResponse<StreamChatGenerics>[];
hidden?: boolean;
membership?: ChannelMemberResponse<StreamChatGenerics> | null;
pending_messages?: PendingMessageResponse<StreamChatGenerics>[];
push_preferences?: PushPreference;
read?: ReadResponse<StreamChatGenerics>[];
threads?: ThreadResponse[];
watcher_count?: number;
watchers?: UserResponse<StreamChatGenerics>[];
};
```
From Go SDK
```go
type queryChannelResponseData struct {
Channel         *Channel         `json:"channel"`
Messages        []*Message …
```
=> [CHA-793] feat: Add pending and pinned messages to query channel response

user.go, user_test.go
https://linear.app/stream/issue/CHA-831/add-restoreusers-method-in-go-sdk
- Added a new RestoreUsers method to the Client struct
- Performs validation to ensure the userIDs array is not empty
- Added unit tests that verify both error and success cases
=> [CHA-831] feat: Implement RestoreUsers functionality and add corresponding tests

common.go, thread.go, thread_test.go
We added support of filter and sort parameter in QueryThreads endpoint. This MR adds the query_thread functionality to be used for client.
```go
limit := 10
query := &QueryThreadsRequest{
Filter: map[string]any{
"channel_cid": map[string]any{
"$eq": ch.CID,
},
},
Sort: &SortParamRequestList{
{
Field:     "created_at",
Direction: -1,
},
},
PagerRequest: PagerRequest{
Limit: &limit,
},
UserID: membersID[0],
}
resp, err := c.QueryThreads(ctx, query)
```
=> [CHA-794] Add Query Threads

message.go, message_test.go
**Add MessageImmediate option for explicit pending=false messaging**
This PR introduces a new MessageImmediate function that explicitly sets the message's pending flag to false. This provides a clearer and more flexible API for users who need to control the pending status of their messages.
Changes:
- Added MessageImmediate function as a counterpart to the existing MessagePending
- Made both functions use the same underlying implementation
- Added unit test to verify the new functionality works as expected
**Why not just remove omitempty?**
Removing the omitempty tag from the Pending field would be a poor solution because:
• It would unnecessarily increase payload size for all requests
• It changes the API contract for all clients
• It would send the "pending" field in all requests even …
=> feat(message): add MessageImmediate option for setting pending=false

message.go
- Adds an optional `force_moderation` field of boolean type to the send message request
Example usage: 
`message, err := channel.SendMessage(ctx, message, userID, WithForceModeration(true))`
=> feat: add optional force_moderation field parameter to the send message request

app.go, app_test.go
- Adding new field `EventHooks` to `AppSetting`
- Handle the error returned when `EventHooks` is set when the system hasn't migrated to hook v2
- Handle the error returned when old fields are set when the system has migrated to hook v2
=> Add EventHooks field to AppSetting

ban_test.go, channel.go, channel_test.go, client.go, client_test.go, draft_test.go, message_history_test.go, message_test.go, query_test.go, thread_test.go, unread_counts_test.go, utils_test.go
The backend already support pass the ChannelMember instead of only the ID, this change aim change to use the whole ChannelMember for create/update channel requests
=> [CHA-941]: supporting passing member
